[{"id":674981101,"node_id":"R_kgDOKDtk7Q","name":"CVE-2018-6789-Python3","full_name":"thistehneisen/CVE-2018-6789-Python3","private":false,"owner":{"login":"thistehneisen","id":6432992,"node_id":"MDQ6VXNlcjY0MzI5OTI=","avatar_url":"https://avatars.githubusercontent.com/u/6432992?v=4","url":"https://api.github.com/users/thistehneisen","html_url":"https://github.com/thistehneisen","type":"User","site_admin":false},"html_url":"https://github.com/thistehneisen/CVE-2018-6789-Python3","description":"Exim \u003c 4.90.1 RCE Vulnerability remake for Python3 with arguments passed from CLI","fork":false,"url":"https://api.github.com/repos/thistehneisen/CVE-2018-6789-Python3","created_at":"2023-08-05T11:28:49Z","updated_at":"2023-08-05T11:29:43Z","pushed_at":"2023-08-05T11:30:52Z","stargazers_count":0,"watchers_count":0,"forks_count":0,"archived":false,"disabled":false,"allow_forking":true,"is_template":false,"topics":[],"visibility":"public","forks":0,"watchers":0,"default_branch":"main","score":1}]