[{"id":786312450,"node_id":"R_kgDOLt4tAg","name":"cve-2020-1938","full_name":"Warelock/cve-2020-1938","private":false,"owner":{"login":"Warelock","id":87372454,"node_id":"MDQ6VXNlcjg3MzcyNDU0","avatar_url":"https://avatars.githubusercontent.com/u/87372454?v=4","url":"https://api.github.com/users/Warelock","html_url":"https://github.com/Warelock","type":"User","site_admin":false},"html_url":"https://github.com/Warelock/cve-2020-1938","description":"cve-2020-1938 Tomcat-Ajp-lfi.git脚本","fork":false,"url":"https://api.github.com/repos/Warelock/cve-2020-1938","created_at":"2024-04-14T04:10:41Z","updated_at":"2024-04-14T05:32:52Z","pushed_at":"2024-04-14T05:32:49Z","stargazers_count":0,"watchers_count":0,"forks_count":0,"archived":false,"disabled":false,"allow_forking":true,"is_template":false,"topics":[],"visibility":"public","forks":0,"watchers":0,"default_branch":"main","score":1},{"id":786291689,"node_id":"R_kgDOLt3b6Q","name":"CVE-2024-24576-PoC-Python","full_name":"mishalhossin/CVE-2024-24576-PoC-Python","private":false,"owner":{"login":"mishalhossin","id":91066601,"node_id":"MDQ6VXNlcjkxMDY2NjAx","avatar_url":"https://avatars.githubusercontent.com/u/91066601?v=4","url":"https://api.github.com/users/mishalhossin","html_url":"https://github.com/mishalhossin","type":"User","site_admin":false},"html_url":"https://github.com/mishalhossin/CVE-2024-24576-PoC-Python","description":"https://nvd.nist.gov/vuln/detail/CVE-2024-24576","fork":false,"url":"https://api.github.com/repos/mishalhossin/CVE-2024-24576-PoC-Python","created_at":"2024-04-14T02:10:55Z","updated_at":"2024-04-14T05:56:42Z","pushed_at":"2024-04-14T02:30:36Z","stargazers_count":0,"watchers_count":0,"forks_count":0,"archived":false,"disabled":false,"allow_forking":true,"is_template":false,"topics":[],"visibility":"public","forks":0,"watchers":0,"default_branch":"main","score":1}]