[{"id":554151760,"node_id":"R_kgDOIQevUA","name":"CVE-2020-0688-Python3","full_name":"1337-llama/CVE-2020-0688-Python3","private":false,"owner":{"login":"1337-llama","id":71475034,"node_id":"MDQ6VXNlcjcxNDc1MDM0","avatar_url":"https://avatars.githubusercontent.com/u/71475034?v=4","url":"https://api.github.com/users/1337-llama","html_url":"https://github.com/1337-llama","type":"User","site_admin":false},"html_url":"https://github.com/1337-llama/CVE-2020-0688-Python3","description":"Exploit updated to use Python 3.","fork":false,"url":"https://api.github.com/repos/1337-llama/CVE-2020-0688-Python3","created_at":"2022-10-19T10:36:10Z","updated_at":"2022-10-20T10:29:58Z","pushed_at":"2023-10-26T18:56:56Z","stargazers_count":2,"watchers_count":2,"forks_count":0,"archived":false,"disabled":false,"allow_forking":true,"is_template":false,"topics":["cve-2020-0688"],"visibility":"public","forks":0,"watchers":2,"default_branch":"main","score":1}]